In [1]:
import numpy as np

In [2]:
#This function find the row that 0 is not the first number in a spesific column and swap between the row with the 0 being 
#the first number and the row that the function found
def swap_rows(matrix, row, column):
    while row <= len(matrix) - 1:
        if matrix[row][column] == 0:
            another_row = row
            while another_row <= len(matrix) - 1:
                if matrix[another_row][column] != 0:
                    matrix[[row, another_row]] = matrix[[another_row, row]]
                another_row += 1
        row += 1

In [3]:
def gauess_method(matrix):
    row = 0
    while row <= len(matrix) - 1:
        swap_rows(matrix, row, row)
        matrix[row] *= (1 / matrix[row][row])
        another_row = 0
        while another_row <= len(matrix) - 1:
            if another_row != row and matrix[another_row][row] != 0:
                matrix[another_row] -= (matrix[another_row][row] * matrix[row]) 
            another_row += 1
        row += 1
    return matrix

In [4]:
arr = np.array([[1, 8, 1, 6, 0], [2, 9, 1, 9, 8], [1, 1, 2, 13, 89], [8, 9, 9, 9, 78]], float)
gauess_method(arr)
print(arr) 
arr_2 = np.array([[2, 7, 21], [2, -4, 10]], float)
gauess_method(arr_2)
print(arr_2)

[[ 1.          0.          0.          0.         -3.97607656]
 [-0.          1.          0.          0.         -5.284689  ]
 [ 0.          0.          1.          0.         11.73205742]
 [-0.         -0.         -0.          1.          5.75358852]]
[[ 1.  0.  7.]
 [-0.  1.  1.]]


In [7]:
#we need the swap_rows function to this matrix for solving it
err_array = np.array([[1, 1, 1, 6], [2, 2, 1, 9], [1, 2, 2, 13]], float)
gauess_method(err_array)

array([[ 1.,  0.,  0., -1.],
       [ 0.,  1.,  0.,  4.],
       [-0., -0.,  1.,  3.]])